### PR TITLE
Organize the README

### PR DESCRIPTION
**Pull request by sgroh**
- Organize the README
- Enrich the documentation
- Add anchor and relative links.

### CODE REVIEW

**Comment by mojitoj** [comment]
I think the docker scrreenshots should be updated to show the ehX demo as well. I prefer we don't have screenshots and just show the output of the `docker ps` or something like that in the text format so that it can be easily versioned, if @ddecouteau is ok with that.

**Comment by sgroh** [comment]
Sure, I will update it tmw.

**Comment by sgroh** [comment]
> ehX demo



> I think the docker scrreenshots should be updated to show the ehX demo as well. I prefer we don't have screenshots and just show the output of the `docker ps` or something like that in the text format so that it can be easily versioned, if @ddecouteau is ok with that.

I have deleted the screenshot to have the text version of what we have on docker containers, now it can be easily versioned.
I have put the docker ps output with all the containers that we have right now in our docker compose. 
Also in the v2-orchestration demo I have added a table with the logic that we are doing in the service, please have a look to it and let me know if there is still something missing on this PR.

**Review by mojitoj — APPROVED** [review]

**Review by ddecouteau — COMMENTED** [review]
docker-compose.yml is incorrect in leap-demos the leap-ces-orchestration image has been replaced with following;
  leap-ces-v2-orchestration:
    image: ddecouteau/leap-ces-v2-orchestration
    container_name: leap-ces-v2-orchestration
    environment:
      CDS_HOST_URL: ${CDS_HOST_URL}
      SLS_HOST_URL: ${SLS_HOST_URL}
      HAPI_FHIR_URL: ${HAPI_FHIR_URL}
    ports:
      - 9092:9092
  
  leap-ces-ccda-orchestration:
    image: ddecouteau/leap-ces-ccda-orchestration
    container_name: leap-ces-ccda-orchestration
    environment:
      CDS_HOST_URL: ${CDS_HOST_URL}
      SLS_HOST_URL: ${SLS_HOST_URL}
      HAPI_FHIR_URL: ${HAPI_FHIR_URL}
    ports:
      - 9093:9093

**Comment by sgroh** [comment]
> docker-compose.yml is incorrect in leap-demos the leap-ces-orchestration image has been replaced with following;
> leap-ces-v2-orchestration:
> image: ddecouteau/leap-ces-v2-orchestration
> container_name: leap-ces-v2-orchestration
> environment:
> CDS_HOST_URL: ${CDS_HOST_URL}
> SLS_HOST_URL: ${SLS_HOST_URL}
> HAPI_FHIR_URL: ${HAPI_FHIR_URL}
> ports:
> - 9092:9092
> 
> leap-ces-ccda-orchestration:
> image: ddecouteau/leap-ces-ccda-orchestration
> container_name: leap-ces-ccda-orchestration
> environment:
> CDS_HOST_URL: ${CDS_HOST_URL}
> SLS_HOST_URL: ${SLS_HOST_URL}
> HAPI_FHIR_URL: ${HAPI_FHIR_URL}
> ports:
> - 9093:9093



> ddecouteau/l

Ok @ddecouteau, sorry, I did not have that topic in my requirements, BTW it' s added and tested (there were some missing env values that I' ve added on missing services) Please have a look now to it. Thanks for your previous comments.

**Review by ddecouteau — APPROVED** [review]

**Pull request merged**
